version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafkaserver
    ports:
      - "9092:9092"
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_HOST_NAME: kafkaserver
      KAFKA_ADVERTISED_HOST_NAME: kafkaserver
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ADVERTISED_PORT: 9092
  spark-master:
    image: singularities/spark
    container_name: spark-master
    command: start-spark master
    hostname: spark-master
    ports:
      - "6066:6066"
      - "7070:7070"
      - "9099:8080"
  spark-worker-1:
    image: singularities/spark
    container_name: spark-worker-1
    command: start-spark worker spark-master
    ports:
    - "8081:8080"
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    links:
      - spark-master
  spark-worker-2:
    image: singularities/spark
    container_name: spark-worker-2
    command: start-spark worker spark-master
    ports:
      - "8082:8080"
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    links:
      - spark-master
