version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - kafkanet
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - "9092:9092"
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_HOST_NAME: kafkaserver
      KAFKA_ADVERTISED_HOST_NAME: kafkaserver
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ADVERTISED_PORT: 9092
  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    ports:
      - "9099:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "4041:4040"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
      - "4042:4040"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

networks:
  kafkanet:
    driver: bridge
